name: test
on:
  push:
    branches:
      - "*"
jobs:
  test:
    name: Test CLI
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    concurrency:
      group: test
      cancel-in-progress: true
    permissions:
      # for testing cli functionality (get commit history)
      contents: read
      # for installing @reflame/lib-resource
      packages: read
      # # for npm publish provenance
      # id-token: write
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.14
      - run: echo "[install.scopes]" > bunfig.toml
      - run: echo "reflame = { url = \"https://npm.pkg.github.com\", token = \"${GITHUB_TOKEN}\" }" >> bunfig.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: bun install
      - run: bun run build
      - run: bun run start
        env:
          REFLAME_SECRET: ${{ secrets.REFLAME_SECRET_DEVELOPMENT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: bun run publish
        if: github.ref == 'refs/heads/main'
      - uses: actions/setup-node@v4
        if: github.ref == 'refs/heads/main'
        with:
          node-version: 18
      - run: cd packages/@reflame/cli && npm publish --access public --provenance
        if: github.ref == 'refs/heads/main'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
